### ISSUE TITLE
Using `PublicKey.createProgramAddress` to create token address (ATA)

### ISSUE THREAD

**Issue by will-yijinin** [p2p-org/solanaj#26]
Hi, tried to use `PublicKey.createProgramAddress` to create token address.
![20220708-162906](https://user-images.githubusercontent.com/81351621/177951419-f82531c6-0122-4eb5-9298-21a0f0cc755c.jpeg)
Got `3QwDKvxDTPo9df9TEFCw95SXK26pHkW1ScKMyVui3i1W`. It's supposed to be `FGnv2TqP42DwXhyxMwgC8dmxzkGjwSp8ysnW88rXSxE9`. Any ideas what is wrong here?

**Comment by lmvdz** [comment]
my fork has token account
